name: jsdocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./calorieTracker
          recurse: true
          output_dir: ./out

          
      - name: Push JSDocs
        run: |
          ls
          git config --global user.name 'shubham-kumar1410'
          git config --global user.email 'shubhamkmr1410@gmail.com'
          git add ./out/*
          git commit -am "Automated docs"
          git push   
