name: jsdocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./calorieTracker
          recurse: true
          output_dir: ./out

          
      - name: Push JSDocs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./out/*
          git commit -am "Automated docs"
          git checkout -b jsdocs-branch
          git push --set-upstream origin jsdocs-branch  
